const ProductsData = [
    {
        id: 1,
        Productsname: "Fire-Boltt Phoenix Smart Watch",
        img: "https://vsprod.vijaysales.com/media/catalog/product/2/2/227197-image1_1.jpg?optimize=medium&fit=bounds&height=500&width=500",
        price: 1599,
        rating: 4.2,
        Catagory: 'Electronics',
    },
    {
        id: 2,
        Productsname: "Redmi 13C 5G (Stardust Black, 4GB RAM, 128GB Storage)",
        img: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSds7bQyKC9mV11Vdq71efY2wecHr1fbQDq1Wb3MAZmsLJ_p0B9trohDp5kag5N2H5lnyzLdrjqQE-O4jpch3tzJS2cjtToig8qfujVDgrQ6wkdDS6J4ErAJLS8vzeFgmOj7syBZ4K7Lw&usqp=CAc",
        price: 10499,
        rating: 4.0,
        Catagory: 'Mobiles',
    },
    {
        id: 3,
        Productsname: "Allen Solly Men's Regular Fit Polo",
        img: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQoD4Ipg2Xl8a64f__UbI-0F8crap0mukq_1gkarjQWrQ08cqaaPcEowEee1LeNYW_LqK6IvlXPX8zv-5YxN6XyIjLNaJDXwg",
        price: 749,
        rating: 4.5,
        Catagory: 'Apparel',
    },
    {
        id: 4,
        Productsname: "Amazon Basics 60 cm (24 inch) HD Ready Smart LED TV",
        img: "https://m.media-amazon.com/images/I/713i5dKk8SL._SX679_.jpg",
        price: 7999,
        rating: 3.8,
        Catagory: 'Electronics',
    },
    {
        id: 5,
        Productsname: "The Power of Your Subconscious Mind (Paperback)",
        img: "https://m.media-amazon.com/images/I/61WMgOHyDaL._SY522_.jpg",
        price: 199,
        rating: 4.6,
        Catagory: 'Books',
    },
    {
        id: 6,
        Productsname: "boAt Rockerz 450 Bluetooth On-Ear Headphones",
        img: "https://www.boat-lifestyle.com/cdn/shop/products/eb8e0fbd-c412-48b3-9c91-5b49ddf35800_600x.png?v=1673002681",
        price: 1299,
        rating: 4.1,
        Catagory: 'Audio',
    },
    {
        id: 7,
        Productsname: "Amazon Brand - Solimo 3-Seater Fabric Sofa",
        img: "https://m.media-amazon.com/images/I/91NtCXw-eRL.jpg",
        price: 14999,
        rating: 4.3,
        Catagory: 'Home Furniture',
    },
    {
        id: 8,
        Productsname: "L'Oreal Paris Hyaluronic Acid Serum",
        img: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTVpvTrlgrP-arZioQGLpjxxl5gRra6F7AZcd2vwvxA2Vk1PaEpYBBdP-jfuPY3fMpoRgk5-roZN62HNSiAc0MsR90VY2keTD5rFn1pnHzM-TA_WWZjO_d6",
        price: 699,
        rating: 4.4,
        Catagory: 'Beauty',
    },
    {
        id: 9,
        Productsname: "Prestige Alpha Deluxe Pressure Cooker, 3 Litres",
        img: "https://m.media-amazon.com/images/I/51i+odv3xOL._SX679_.jpg",
        price: 1750,
        rating: 4.2,
        Catagory: 'Kitchen',
    },
    {
        id: 10,
        Productsname: "Hasbro Monopoly Classic Edition",
        img: "https://shopbefikar.com/wp-content/uploads/2023/11/monopoly-india-edition-board-game-small-4.jpg.webp",
        price: 999,
        rating: 4.7,
        Catagory: 'Toys',
    },
    {
        id: 11,
        Productsname: "Mi 33W SonicCharge 2.0 Charger Combo",
        img: "https://m.media-amazon.com/images/I/51oepOPIPmL._SX679_.jpg",
        price: 1199,
        rating: 4.1,
        Catagory: 'Accessories',
    },
    {
        id: 12,
        Productsname: "HP Laptop 15s (i5, 16GB RAM, 512GB SSD)",
        img: "https://p1-ofp.static.pub/medias/25565228746_IdeaPadSlim3ArcticGreyIMG_202301091224261732122932484.png",
        price: 54990,
        rating: 4.0,
        Catagory: 'Laptops',
    },
];

export default ProductsData;